format_version: 3
pipelines:
  appkeepm:
    environment_variables:
      AWS_PROFILE: "keeBeta"
      AWS_REGION: "eu-west-2"
    group: frontend
    materials:
      mygit:
        type: configrepo
      keeFrontendDependency:
        pipeline: keeFrontend
        stage: installBuildTestAndPublish
      kprpcDependency:
        pipeline: kprpc
        stage: installBuildTestAndPublish
    stages:
      - installBuildTestAndPublish:
          tasks:
            - exec:
                command: npm
                arguments:
                    - "ci"
            - exec:
                command: npm
                arguments:
                    - "run"
                    - "prod"
            - exec:
                command: /bin/bash
                arguments:
                    - "-c"
                    - "aws s3 sync dist/ s3://app-beta.kee.pm"
            - exec:
                command: /bin/bash
                arguments:
                    - "-c"
                    - "aws cloudfront create-invalidation --distribution-id E3FJWMTO2ETM37 --paths /\\*"
  appkeepmProduction:
    environment_variables:
      AWS_PROFILE: "keeProd"
      AWS_REGION: "eu-west-2"
    group: frontend
    materials:
      mygit:
        type: configrepo
      appkeepmDependency:
        pipeline: appkeepm
        stage: installBuildTestAndPublish
    stages:
      - pause:
          tasks:
            - exec:
                command: pwd
      - installBuildTestAndPublish:
          approval: manual
          tasks:
            - exec:
                command: npm
                arguments:
                  - "ci"
            - exec:
                command: npm
                arguments:
                    - "run"
                    - "prod"
            - exec:
                command: /bin/bash
                arguments:
                    - "-c"
                    - "aws s3 sync dist/ s3://keevault.pm"
            - exec:
                command: /bin/bash
                arguments:
                    - "-c"
                    - "aws cloudfront create-invalidation --distribution-id E2RDOCYD2M73CI --paths /\\*"

# Encrypted vars in GoCD are very clunky. Recreate as needed by using this hack:
# curl 'https://cd.kee.pm:8154/go/api/admin/encrypt' --insecure -u 'username:password' -H 'Accept: application/vnd.go.cd.v1+json' -H 'Content-Type: application/json' -X POST -d '{"value": "badger"}'
# response:
# {
#   "_links" : {
#     "doc" : {
#       "href" : "https://api.gocd.org/#encryption"
#     },
#     "self" : {
#       "href" : "https://cd.kee.pm:8154/go/api/admin/encrypt"
#     }
#   },
#   "encrypted_value" : "AES:..."
# }
